
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hca
 */
public class MatrixFrame extends javax.swing.JFrame {

    /**
     * Creates new form MatrixFrame
     */
    public MatrixFrame() {
        initComponents();
        initActionListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        Grid = new javax.swing.JPanel();
        Grid1 = new javax.swing.JPanel();
        jbGrid00 = new javax.swing.JButton();
        jbGrid01 = new javax.swing.JButton();
        jbGrid02 = new javax.swing.JButton();
        jbGrid10 = new javax.swing.JButton();
        jbGrid11 = new javax.swing.JButton();
        jbGrid12 = new javax.swing.JButton();
        jbGrid20 = new javax.swing.JButton();
        jbGrid21 = new javax.swing.JButton();
        jbGrid22 = new javax.swing.JButton();
        Grid2 = new javax.swing.JPanel();
        jbGrid03 = new javax.swing.JButton();
        jbGrid04 = new javax.swing.JButton();
        jbGrid05 = new javax.swing.JButton();
        jbGrid13 = new javax.swing.JButton();
        jbGrid14 = new javax.swing.JButton();
        jbGrid15 = new javax.swing.JButton();
        jbGrid23 = new javax.swing.JButton();
        jbGrid24 = new javax.swing.JButton();
        jbGrid25 = new javax.swing.JButton();
        Grid3 = new javax.swing.JPanel();
        jbGrid06 = new javax.swing.JButton();
        jbGrid07 = new javax.swing.JButton();
        jbGrid08 = new javax.swing.JButton();
        jbGrid16 = new javax.swing.JButton();
        jbGrid17 = new javax.swing.JButton();
        jbGrid18 = new javax.swing.JButton();
        jbGrid26 = new javax.swing.JButton();
        jbGrid27 = new javax.swing.JButton();
        jbGrid28 = new javax.swing.JButton();
        Grid4 = new javax.swing.JPanel();
        jbGrid30 = new javax.swing.JButton();
        jbGrid31 = new javax.swing.JButton();
        jbGrid32 = new javax.swing.JButton();
        jbGrid40 = new javax.swing.JButton();
        jbGrid41 = new javax.swing.JButton();
        jbGrid42 = new javax.swing.JButton();
        jbGrid50 = new javax.swing.JButton();
        jbGrid51 = new javax.swing.JButton();
        jbGrid52 = new javax.swing.JButton();
        Grid5 = new javax.swing.JPanel();
        jbGrid33 = new javax.swing.JButton();
        jbGrid34 = new javax.swing.JButton();
        jbGrid35 = new javax.swing.JButton();
        jbGrid43 = new javax.swing.JButton();
        jbGrid44 = new javax.swing.JButton();
        jbGrid45 = new javax.swing.JButton();
        jbGrid53 = new javax.swing.JButton();
        jbGrid54 = new javax.swing.JButton();
        jbGrid55 = new javax.swing.JButton();
        Grid6 = new javax.swing.JPanel();
        jbGrid36 = new javax.swing.JButton();
        jbGrid37 = new javax.swing.JButton();
        jbGrid38 = new javax.swing.JButton();
        jbGrid46 = new javax.swing.JButton();
        jbGrid47 = new javax.swing.JButton();
        jbGrid48 = new javax.swing.JButton();
        jbGrid56 = new javax.swing.JButton();
        jbGrid57 = new javax.swing.JButton();
        jbGrid58 = new javax.swing.JButton();
        Grid7 = new javax.swing.JPanel();
        jbGrid60 = new javax.swing.JButton();
        jbGrid61 = new javax.swing.JButton();
        jbGrid62 = new javax.swing.JButton();
        jbGrid70 = new javax.swing.JButton();
        jbGrid71 = new javax.swing.JButton();
        jbGrid72 = new javax.swing.JButton();
        jbGrid80 = new javax.swing.JButton();
        jbGrid81 = new javax.swing.JButton();
        jbGrid82 = new javax.swing.JButton();
        Grid8 = new javax.swing.JPanel();
        jbGrid63 = new javax.swing.JButton();
        jbGrid64 = new javax.swing.JButton();
        jbGrid65 = new javax.swing.JButton();
        jbGrid73 = new javax.swing.JButton();
        jbGrid74 = new javax.swing.JButton();
        jbGrid75 = new javax.swing.JButton();
        jbGrid83 = new javax.swing.JButton();
        jbGrid84 = new javax.swing.JButton();
        jbGrid85 = new javax.swing.JButton();
        Grid9 = new javax.swing.JPanel();
        jbGrid66 = new javax.swing.JButton();
        jbGrid67 = new javax.swing.JButton();
        jbGrid68 = new javax.swing.JButton();
        jbGrid76 = new javax.swing.JButton();
        jbGrid77 = new javax.swing.JButton();
        jbGrid78 = new javax.swing.JButton();
        jbGrid86 = new javax.swing.JButton();
        jbGrid87 = new javax.swing.JButton();
        jbGrid88 = new javax.swing.JButton();
        Botones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jFileChooser1.setCurrentDirectory(new java.io.File("E:\\Proyecto2\\src\\TestFiles"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        Grid.setMinimumSize(new java.awt.Dimension(117, 237));
        Grid.setLayout(new java.awt.GridLayout(3, 3, 15, 15));

        Grid1.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid1.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid1.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid00.setText("0");
        Grid1.add(jbGrid00);

        jbGrid01.setText("0");
        jbGrid01.setToolTipText("");
        Grid1.add(jbGrid01);

        jbGrid02.setText("0");
        Grid1.add(jbGrid02);

        jbGrid10.setText("0");
        Grid1.add(jbGrid10);

        jbGrid11.setText("0");
        jbGrid11.setToolTipText("");
        Grid1.add(jbGrid11);

        jbGrid12.setText("0");
        Grid1.add(jbGrid12);

        jbGrid20.setText("0");
        Grid1.add(jbGrid20);

        jbGrid21.setText("0");
        Grid1.add(jbGrid21);

        jbGrid22.setText("0");
        jbGrid22.setToolTipText("");
        jbGrid22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid22ActionPerformed(evt);
            }
        });
        Grid1.add(jbGrid22);

        Grid.add(Grid1);

        Grid2.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid2.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid2.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid03.setText("0");
        Grid2.add(jbGrid03);

        jbGrid04.setText("0");
        jbGrid04.setToolTipText("");
        Grid2.add(jbGrid04);

        jbGrid05.setText("0");
        Grid2.add(jbGrid05);

        jbGrid13.setText("0");
        Grid2.add(jbGrid13);

        jbGrid14.setText("0");
        jbGrid14.setToolTipText("");
        Grid2.add(jbGrid14);

        jbGrid15.setBackground(new java.awt.Color(255, 102, 102));
        jbGrid15.setText("0");
        Grid2.add(jbGrid15);

        jbGrid23.setText("0");
        Grid2.add(jbGrid23);

        jbGrid24.setText("0");
        Grid2.add(jbGrid24);

        jbGrid25.setText("0");
        jbGrid25.setToolTipText("");
        jbGrid25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid25ActionPerformed(evt);
            }
        });
        Grid2.add(jbGrid25);

        Grid.add(Grid2);

        Grid3.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid3.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid3.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid06.setText("0");
        Grid3.add(jbGrid06);

        jbGrid07.setText("0");
        jbGrid07.setToolTipText("");
        Grid3.add(jbGrid07);

        jbGrid08.setText("0");
        Grid3.add(jbGrid08);

        jbGrid16.setText("0");
        Grid3.add(jbGrid16);

        jbGrid17.setText("0");
        jbGrid17.setToolTipText("");
        Grid3.add(jbGrid17);

        jbGrid18.setText("0");
        Grid3.add(jbGrid18);

        jbGrid26.setText("0");
        Grid3.add(jbGrid26);

        jbGrid27.setText("0");
        Grid3.add(jbGrid27);

        jbGrid28.setText("0");
        jbGrid28.setToolTipText("");
        jbGrid28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid28ActionPerformed(evt);
            }
        });
        Grid3.add(jbGrid28);

        Grid.add(Grid3);

        Grid4.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid4.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid4.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid30.setText("0");
        Grid4.add(jbGrid30);

        jbGrid31.setText("0");
        jbGrid31.setToolTipText("");
        Grid4.add(jbGrid31);

        jbGrid32.setText("0");
        Grid4.add(jbGrid32);

        jbGrid40.setText("0");
        Grid4.add(jbGrid40);

        jbGrid41.setText("0");
        jbGrid41.setToolTipText("");
        Grid4.add(jbGrid41);

        jbGrid42.setText("0");
        Grid4.add(jbGrid42);

        jbGrid50.setText("0");
        Grid4.add(jbGrid50);

        jbGrid51.setText("0");
        Grid4.add(jbGrid51);

        jbGrid52.setText("0");
        jbGrid52.setToolTipText("");
        jbGrid52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid52ActionPerformed(evt);
            }
        });
        Grid4.add(jbGrid52);

        Grid.add(Grid4);

        Grid5.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid5.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid5.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid33.setText("0");
        Grid5.add(jbGrid33);

        jbGrid34.setText("0");
        jbGrid34.setToolTipText("");
        Grid5.add(jbGrid34);

        jbGrid35.setText("0");
        Grid5.add(jbGrid35);

        jbGrid43.setText("0");
        Grid5.add(jbGrid43);

        jbGrid44.setText("0");
        jbGrid44.setToolTipText("");
        Grid5.add(jbGrid44);

        jbGrid45.setText("0");
        Grid5.add(jbGrid45);

        jbGrid53.setText("0");
        Grid5.add(jbGrid53);

        jbGrid54.setText("0");
        Grid5.add(jbGrid54);

        jbGrid55.setText("0");
        jbGrid55.setToolTipText("");
        jbGrid55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid55ActionPerformed(evt);
            }
        });
        Grid5.add(jbGrid55);

        Grid.add(Grid5);

        Grid6.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid6.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid6.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid36.setText("0");
        Grid6.add(jbGrid36);

        jbGrid37.setText("0");
        jbGrid37.setToolTipText("");
        Grid6.add(jbGrid37);

        jbGrid38.setText("0");
        Grid6.add(jbGrid38);

        jbGrid46.setText("0");
        Grid6.add(jbGrid46);

        jbGrid47.setText("0");
        jbGrid47.setToolTipText("");
        Grid6.add(jbGrid47);

        jbGrid48.setText("0");
        Grid6.add(jbGrid48);

        jbGrid56.setText("0");
        Grid6.add(jbGrid56);

        jbGrid57.setText("0");
        Grid6.add(jbGrid57);

        jbGrid58.setText("0");
        jbGrid58.setToolTipText("");
        jbGrid58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid58ActionPerformed(evt);
            }
        });
        Grid6.add(jbGrid58);

        Grid.add(Grid6);

        Grid7.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid7.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid7.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid60.setText("0");
        jbGrid60.setDoubleBuffered(true);
        Grid7.add(jbGrid60);

        jbGrid61.setText("0");
        jbGrid61.setToolTipText("");
        Grid7.add(jbGrid61);

        jbGrid62.setText("0");
        Grid7.add(jbGrid62);

        jbGrid70.setText("0");
        Grid7.add(jbGrid70);

        jbGrid71.setText("0");
        jbGrid71.setToolTipText("");
        Grid7.add(jbGrid71);

        jbGrid72.setText("0");
        Grid7.add(jbGrid72);

        jbGrid80.setText("0");
        jbGrid80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid80ActionPerformed(evt);
            }
        });
        Grid7.add(jbGrid80);

        jbGrid81.setText("0");
        Grid7.add(jbGrid81);

        jbGrid82.setText("0");
        jbGrid82.setToolTipText("");
        jbGrid82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid82ActionPerformed(evt);
            }
        });
        Grid7.add(jbGrid82);

        Grid.add(Grid7);

        Grid8.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid8.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid8.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid63.setText("0");
        Grid8.add(jbGrid63);

        jbGrid64.setText("0");
        jbGrid64.setToolTipText("");
        Grid8.add(jbGrid64);

        jbGrid65.setText("0");
        Grid8.add(jbGrid65);

        jbGrid73.setText("0");
        Grid8.add(jbGrid73);

        jbGrid74.setText("0");
        jbGrid74.setToolTipText("");
        Grid8.add(jbGrid74);

        jbGrid75.setText("0");
        Grid8.add(jbGrid75);

        jbGrid83.setText("0");
        jbGrid83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid83ActionPerformed(evt);
            }
        });
        Grid8.add(jbGrid83);

        jbGrid84.setText("0");
        Grid8.add(jbGrid84);

        jbGrid85.setText("0");
        jbGrid85.setToolTipText("");
        jbGrid85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid85ActionPerformed(evt);
            }
        });
        Grid8.add(jbGrid85);

        Grid.add(Grid8);

        Grid9.setMaximumSize(new java.awt.Dimension(110, 110));
        Grid9.setMinimumSize(new java.awt.Dimension(110, 110));
        Grid9.setLayout(new java.awt.GridLayout(3, 3));

        jbGrid66.setText("0");
        Grid9.add(jbGrid66);

        jbGrid67.setText("0");
        jbGrid67.setToolTipText("");
        Grid9.add(jbGrid67);

        jbGrid68.setText("0");
        Grid9.add(jbGrid68);

        jbGrid76.setText("0");
        Grid9.add(jbGrid76);

        jbGrid77.setText("0");
        jbGrid77.setToolTipText("");
        Grid9.add(jbGrid77);

        jbGrid78.setText("0");
        Grid9.add(jbGrid78);

        jbGrid86.setText("0");
        jbGrid86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid86ActionPerformed(evt);
            }
        });
        Grid9.add(jbGrid86);

        jbGrid87.setText("0");
        Grid9.add(jbGrid87);

        jbGrid88.setText("0");
        jbGrid88.setToolTipText("");
        jbGrid88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrid88ActionPerformed(evt);
            }
        });
        Grid9.add(jbGrid88);

        Grid.add(Grid9);

        jButton1.setText("1");

        jButton2.setText("2");
        jButton2.setToolTipText("");

        jButton3.setText("3");

        jButton4.setText("4");

        jButton5.setText("5");
        jButton5.setToolTipText("");

        jButton6.setText("6");

        jButton7.setText("9");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("7");

        jButton9.setText("8");
        jButton9.setToolTipText("");

        jLabel1.setText("Celda: ");

        jButton11.setAction(new ClearAction());
        jButton11.setText("Clear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("0");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setAction(new SolveAction());
        jButton13.setText("Solve");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton10.setText("Open From File");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout BotonesLayout = new javax.swing.GroupLayout(Botones);
        Botones.setLayout(BotonesLayout);
        BotonesLayout.setHorizontalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BotonesLayout.createSequentialGroup()
                            .addComponent(jButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6))
                        .addGroup(BotonesLayout.createSequentialGroup()
                            .addComponent(jButton8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton7))
                        .addComponent(jLabel1)
                        .addGroup(BotonesLayout.createSequentialGroup()
                            .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BotonesLayout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3))
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        BotonesLayout.setVerticalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonesLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Grid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jbGrid22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid22ActionPerformed

    private void jbGrid25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid25ActionPerformed

    private void jbGrid28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid28ActionPerformed

    private void jbGrid52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid52ActionPerformed

    private void jbGrid55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid55ActionPerformed

    private void jbGrid58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid58ActionPerformed

    private void jbGrid82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid82ActionPerformed

    private void jbGrid80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid80ActionPerformed

    private void jbGrid83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid83ActionPerformed

    private void jbGrid85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid85ActionPerformed

    private void jbGrid86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid86ActionPerformed

    private void jbGrid88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrid88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGrid88ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed
    
    /*
     *Funciones para pruebas
     */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        JFileChooser fc;
        fc = jFileChooser1;
	fc.showOpenDialog(null);
        File archivo = fc.getSelectedFile();
        sudo = sudoFromFile(archivo);
        setGrid();
    }//GEN-LAST:event_jButton10ActionPerformed
    
    private static Sudoku sudoFromFile(File arch){
        Scanner scan;
        try {
            scan = new Scanner(arch);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MatrixFrame.class.getName()).log(Level.SEVERE, null, ex);
            scan = null;
        }
        Sudoku newSudo = new Sudoku();
        for(int i = 0; i < 9; i++)
            for(int j = 0; j < 9; j++){
                newSudo.insertaNumero(scan.nextInt() , new Celda(i,j));
            }
        return newSudo;
    }
    
    private void printGrid(){
        int[][] migrid;
        migrid = sudo.getGrid().clone();
        
        for(int i = 0; i < 9; i++){
            for(int j = 0; j < 9; j++)
                System.out.print(migrid[i][j] + "  ");
            System.out.println();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrixFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Grid;
    private javax.swing.JPanel Grid1;
    private javax.swing.JPanel Grid2;
    private javax.swing.JPanel Grid3;
    private javax.swing.JPanel Grid4;
    private javax.swing.JPanel Grid5;
    private javax.swing.JPanel Grid6;
    private javax.swing.JPanel Grid7;
    private javax.swing.JPanel Grid8;
    private javax.swing.JPanel Grid9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbGrid00;
    private javax.swing.JButton jbGrid01;
    private javax.swing.JButton jbGrid02;
    private javax.swing.JButton jbGrid03;
    private javax.swing.JButton jbGrid04;
    private javax.swing.JButton jbGrid05;
    private javax.swing.JButton jbGrid06;
    private javax.swing.JButton jbGrid07;
    private javax.swing.JButton jbGrid08;
    private javax.swing.JButton jbGrid10;
    private javax.swing.JButton jbGrid11;
    private javax.swing.JButton jbGrid12;
    private javax.swing.JButton jbGrid13;
    private javax.swing.JButton jbGrid14;
    private javax.swing.JButton jbGrid15;
    private javax.swing.JButton jbGrid16;
    private javax.swing.JButton jbGrid17;
    private javax.swing.JButton jbGrid18;
    private javax.swing.JButton jbGrid20;
    private javax.swing.JButton jbGrid21;
    private javax.swing.JButton jbGrid22;
    private javax.swing.JButton jbGrid23;
    private javax.swing.JButton jbGrid24;
    private javax.swing.JButton jbGrid25;
    private javax.swing.JButton jbGrid26;
    private javax.swing.JButton jbGrid27;
    private javax.swing.JButton jbGrid28;
    private javax.swing.JButton jbGrid30;
    private javax.swing.JButton jbGrid31;
    private javax.swing.JButton jbGrid32;
    private javax.swing.JButton jbGrid33;
    private javax.swing.JButton jbGrid34;
    private javax.swing.JButton jbGrid35;
    private javax.swing.JButton jbGrid36;
    private javax.swing.JButton jbGrid37;
    private javax.swing.JButton jbGrid38;
    private javax.swing.JButton jbGrid40;
    private javax.swing.JButton jbGrid41;
    private javax.swing.JButton jbGrid42;
    private javax.swing.JButton jbGrid43;
    private javax.swing.JButton jbGrid44;
    private javax.swing.JButton jbGrid45;
    private javax.swing.JButton jbGrid46;
    private javax.swing.JButton jbGrid47;
    private javax.swing.JButton jbGrid48;
    private javax.swing.JButton jbGrid50;
    private javax.swing.JButton jbGrid51;
    private javax.swing.JButton jbGrid52;
    private javax.swing.JButton jbGrid53;
    private javax.swing.JButton jbGrid54;
    private javax.swing.JButton jbGrid55;
    private javax.swing.JButton jbGrid56;
    private javax.swing.JButton jbGrid57;
    private javax.swing.JButton jbGrid58;
    private javax.swing.JButton jbGrid60;
    private javax.swing.JButton jbGrid61;
    private javax.swing.JButton jbGrid62;
    private javax.swing.JButton jbGrid63;
    private javax.swing.JButton jbGrid64;
    private javax.swing.JButton jbGrid65;
    private javax.swing.JButton jbGrid66;
    private javax.swing.JButton jbGrid67;
    private javax.swing.JButton jbGrid68;
    private javax.swing.JButton jbGrid70;
    private javax.swing.JButton jbGrid71;
    private javax.swing.JButton jbGrid72;
    private javax.swing.JButton jbGrid73;
    private javax.swing.JButton jbGrid74;
    private javax.swing.JButton jbGrid75;
    private javax.swing.JButton jbGrid76;
    private javax.swing.JButton jbGrid77;
    private javax.swing.JButton jbGrid78;
    private javax.swing.JButton jbGrid80;
    private javax.swing.JButton jbGrid81;
    private javax.swing.JButton jbGrid82;
    private javax.swing.JButton jbGrid83;
    private javax.swing.JButton jbGrid84;
    private javax.swing.JButton jbGrid85;
    private javax.swing.JButton jbGrid86;
    private javax.swing.JButton jbGrid87;
    private javax.swing.JButton jbGrid88;
    // End of variables declaration//GEN-END:variables
    
    
    private Sudoku sudo;
    private Celda celdaAct;
    private ArraySet<Integer> numerosPosibles;
    private JButton[] botones;
    private JButton[][] botonesGrid;
    private final Color DEFAULT_BUTTON_COLOR = new Color(240,240,240);
    private final Color OTHER_BUTTON_COLOR = new Color(255, 102, 102);
    private final Color SELECTED_BUTTON_COLOR = new Color(204, 255, 255);
    private void initActionListeners(){
        sudo = new Sudoku();
        numerosPosibles = new ArraySet(9);
        celdaAct = new Celda(0,0);
        //Asignamos todos los botones a un arreglo para manejarlos mas facilmente
        asignaBotones();
        asignaAcciones();
        setGrid();
    }
    
    private void asignaBotones(){
        botones = new JButton[10];
        botones[0] = jButton12;
        botones[1] = jButton1;
        botones[2] = jButton2;
        botones[3] = jButton3;
        botones[4] = jButton4;
        botones[5] = jButton5;
        botones[6] = jButton6;
        botones[7] = jButton8;
        botones[8] = jButton9;
        botones[9] = jButton7;
        botonesGrid = new JButton[9][9];
        botonesGrid[0][0]=jbGrid00;
        botonesGrid[0][1]=jbGrid01;
        botonesGrid[0][2]=jbGrid02;
        botonesGrid[0][3]=jbGrid03;
        botonesGrid[0][4]=jbGrid04;
        botonesGrid[0][5]=jbGrid05;
        botonesGrid[0][6]=jbGrid06;
        botonesGrid[0][7]=jbGrid07;
        botonesGrid[0][8]=jbGrid08;
        botonesGrid[1][0]=jbGrid10;
        botonesGrid[1][1]=jbGrid11;
        botonesGrid[1][2]=jbGrid12;
        botonesGrid[1][3]=jbGrid13;
        botonesGrid[1][4]=jbGrid14;
        botonesGrid[1][5]=jbGrid15;
        botonesGrid[1][6]=jbGrid16;
        botonesGrid[1][7]=jbGrid17;
        botonesGrid[1][8]=jbGrid18;
        botonesGrid[2][0]=jbGrid20;
        botonesGrid[2][1]=jbGrid21;
        botonesGrid[2][2]=jbGrid22;
        botonesGrid[2][3]=jbGrid23;
        botonesGrid[2][4]=jbGrid24;
        botonesGrid[2][5]=jbGrid25;
        botonesGrid[2][6]=jbGrid26;
        botonesGrid[2][7]=jbGrid27;
        botonesGrid[2][8]=jbGrid28;
        botonesGrid[3][0]=jbGrid30;
        botonesGrid[3][1]=jbGrid31;
        botonesGrid[3][2]=jbGrid32;
        botonesGrid[3][3]=jbGrid33;
        botonesGrid[3][4]=jbGrid34;
        botonesGrid[3][5]=jbGrid35;
        botonesGrid[3][6]=jbGrid36;
        botonesGrid[3][7]=jbGrid37;
        botonesGrid[3][8]=jbGrid38;
        botonesGrid[4][0]=jbGrid40;
        botonesGrid[4][1]=jbGrid41;
        botonesGrid[4][2]=jbGrid42;
        botonesGrid[4][3]=jbGrid43;
        botonesGrid[4][4]=jbGrid44;
        botonesGrid[4][5]=jbGrid45;
        botonesGrid[4][6]=jbGrid46;
        botonesGrid[4][7]=jbGrid47;
        botonesGrid[4][8]=jbGrid48;
        botonesGrid[5][0]=jbGrid50;
        botonesGrid[5][1]=jbGrid51;
        botonesGrid[5][2]=jbGrid52;
        botonesGrid[5][3]=jbGrid53;
        botonesGrid[5][4]=jbGrid54;
        botonesGrid[5][5]=jbGrid55;
        botonesGrid[5][6]=jbGrid56;
        botonesGrid[5][7]=jbGrid57;
        botonesGrid[5][8]=jbGrid58;
        botonesGrid[6][0]=jbGrid60;
        botonesGrid[6][1]=jbGrid61;
        botonesGrid[6][2]=jbGrid62;
        botonesGrid[6][3]=jbGrid63;
        botonesGrid[6][4]=jbGrid64;
        botonesGrid[6][5]=jbGrid65;
        botonesGrid[6][6]=jbGrid66;
        botonesGrid[6][7]=jbGrid67;
        botonesGrid[6][8]=jbGrid68;
        botonesGrid[7][0]=jbGrid70;
        botonesGrid[7][1]=jbGrid71;
        botonesGrid[7][2]=jbGrid72;
        botonesGrid[7][3]=jbGrid73;
        botonesGrid[7][4]=jbGrid74;
        botonesGrid[7][5]=jbGrid75;
        botonesGrid[7][6]=jbGrid76;
        botonesGrid[7][7]=jbGrid77;
        botonesGrid[7][8]=jbGrid78;
        botonesGrid[8][0]=jbGrid80;
        botonesGrid[8][1]=jbGrid81;
        botonesGrid[8][2]=jbGrid82;
        botonesGrid[8][3]=jbGrid83;
        botonesGrid[8][4]=jbGrid84;
        botonesGrid[8][5]=jbGrid85;
        botonesGrid[8][6]=jbGrid86;
        botonesGrid[8][7]=jbGrid87;
        botonesGrid[8][8]=jbGrid88;
    }
    private void asignaAcciones(){
        //Numeros
        enableButtons();
        //grid
        for(int i = 0; i < 9; i++)
            for(int j = 0; j < 9; j++)
                botonesGrid[i][j].setAction(new GridButtonAction(i,j));
    }
    private void enableButtons(){
        botones[0].setAction(new NumberButtonAction(0, true));
            botones[0].setText(""+0);
        for(int i = 1; i < 10; i++){
            botones[i].setAction(new NumberButtonAction(i, numerosPosibles.contains(i)));
            botones[i].setText(""+(i));
        }
    }
    //Lee todos los valores de la matriz de valores
    //pinta de rojo los que son iguales a la seleccion actual
    private void setGrid(){
        int curr = sudo.getVal(celdaAct);
        for(int i = 0; i < 9; i++)
            for(int j = 0; j < 9; j++){
                if(curr == sudo.getVal(j,i))
                    botonesGrid[i][j].setBackground(OTHER_BUTTON_COLOR);
                else
                    botonesGrid[i][j].setBackground(DEFAULT_BUTTON_COLOR);
                botonesGrid[i][j].setText(""+sudo.getVal(j,i));
            }
        botonesGrid[celdaAct.getRow()][celdaAct.getCol()].setBackground(SELECTED_BUTTON_COLOR);
    }
    //Hace lo mismo que la pasada pero pinta de rojo algun numero
    //se usa para cuando el usuario selecciona un valor que no cabe
    //pinta de rojo los que son iguales para que sea evidente porque no se puede
    private void setGrid(int curr){
        for(int i = 0; i < 9; i++)
            for(int j = 0; j < 9; j++){
                if(curr == sudo.getVal(j,i))
                    botonesGrid[i][j].setBackground(OTHER_BUTTON_COLOR);
                else
                    botonesGrid[i][j].setBackground(DEFAULT_BUTTON_COLOR);
                botonesGrid[i][j].setText(""+sudo.getVal(j,i));
                    
            }
        botonesGrid[celdaAct.getRow()][celdaAct.getCol()].setBackground(SELECTED_BUTTON_COLOR);
    }
    
    
    /*
     * Acciones para los botones
     */
    class GridButtonAction extends AbstractAction{
        int col, row;
        public GridButtonAction(int row, int col){
            super();
            this.col = col;
            this.row = row;
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            //System.out.println("("+row+", "+col+")");
            celdaAct = new Celda(row, col);
            numerosPosibles = sudo.numerosPosibles(celdaAct);
            jLabel1.setText("Celda: " + "(" + row + ", " + col + ")");
            enableButtons();
            setGrid();
        }
    }
    
    class  NumberButtonAction extends AbstractAction{
        int num;
        boolean valid;
        
        public NumberButtonAction(int num, boolean valid){
            super();
            this.num = num;
            this.valid = valid;
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            if(valid){
                jLabel2.setVisible(false);
                if(num!=0)
                    sudo.insertaNumero(num, celdaAct);
                else
                    sudo.borraCelda(celdaAct);
                setGrid();
                printGrid();
            }else{
                jLabel2.setVisible(true);
                jLabel2.setText("El numero " + num + " no es valido.");
                setGrid(num);
            }
        }
        
    }
    
    class SolveAction extends AbstractAction{
        @Override
        public void actionPerformed(ActionEvent e) {
            if(!sudo.solveSudo()){
                jLabel2.setText("No se encontro solucion");
                jLabel2.setVisible(true);
            }
            setGrid();
        }
    }
    class ClearAction extends AbstractAction{
        @Override
        public void actionPerformed(ActionEvent e) {
            sudo = new Sudoku();
            setGrid();
        }
    }
    
}
